TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/urls.py
from django.urls import path
from . import views

app_name = 'IntekMovieFridayPollapp'
urlpatterns = [
    # ex: /IntekMovieFridayPollapp/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /IntekMovieFridayPollapp/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /IntekMovieFridayPollapp/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /IntekMovieFridayPollapp/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

TheIntekMovieFridayNightPoll/TheIntekMovieFridayNightPoll/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('IntekMovieFridayPollapp/', include('IntekMovieFridayPollapp.urls')),
    path('admin/', admin.site.urls),
]

TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'IntekMovieFridayPollapp/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'IntekMovieFridayPollapp/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'IntekMovieFridayPollapp/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'IntekMovieFridayPollapp/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('IntekMovieFridayPollapp:results', args=(question.id,)))

TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/templates/IntekMovieFridayPollapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Intek Movie Friday Night Poll</title>
</head>

<body class="flex-column">
<div class="header text-center mb-lg-5">
{#    <h1>The Intek Movie Friday Night Poll</h1>#}
    <img src="{{ STATIC_URL }}IntekMovieFridayPollapp/images/text.gif" alt="header">
</div>
<div class="container pt-5 d-flex justify-content-center">
{#    <div class="col-4"></div>#}
    <div class="card rounded">
        <div class="card-header text-center my-3">
            <img class="logo w-75" src="{{ STATIC_URL }}IntekMovieFridayPollapp/images/logo.png" alt="logo">
        </div>
        <div class="card-body d-flex flex-column justify-content-center mb-4 pt-0">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{{ STATIC_URL }}IntekMovieFridayPollapp/style.css">
</body>
</html>

TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/templates/IntekMovieFridayPollapp/detail.html
{% extends 'IntekMovieFridayPollapp/base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'IntekMovieFridayPollapp/style.css' %}"/>
    <div class="poll">
        <h4 class="mb-3">{{ question.question_text }}</h4>
    </div>

    {% if error_message %}<p class="text-danger"><strong>{{ error_message }}</strong></p>{% endif %}

    <form class="p-3" action="{% url 'IntekMovieFridayPollapp:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <button type="button" class="list-group-item list-group-item-action py-2 d-inline-flex mb-3">
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
                <div class="col-12">
                    <label class="flex-wrap" style="color: black; margin: 0; width: 100%"
                           for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                </div>
            </button>
        {% endfor %}
        <in class="d-flex justify-content-between">
            <input id="voteButton" class="rounded col-2 mt-4" type="submit" value="Vote"/>
            <a href="{% url 'IntekMovieFridayPollapp:index' %}" id="backButton" class="rounded col-2 text-dark mt-4">Back</a>

            </div>
    </form>

{% endblock %}

TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/templates/IntekMovieFridayPollapp/index.html
{% extends 'IntekMovieFridayPollapp/base.html' %}

{% block content %}
    <div class="pb-0 pl-0 mb-4">
        <h4 class="text-light mb-0">Choose a Movie Friday to vote</h4>
    </div>
    {% if latest_question_list %}
        <div class="list-group">
            {% for question in latest_question_list %}
                <button type="button" class="list-group-item list-group-item-action">
                    <a href="{% url 'IntekMovieFridayPollapp:detail' question.id %}"
                       style="color: #19191a">{{ question.question_text }}</a>
                </button>
            {% endfor %}
        </div>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

TheIntekMovieFridayNightPoll/IntekMovieFridayPollapp/templates/IntekMovieFridayPollapp/results.html
{% extends 'IntekMovieFridayPollapp/base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'IntekMovieFridayPollapp/style.css' %}"/>

    <h4 class="text-light pb-4">Results for {{ question.question_text }}</h4>

    <ul>
        {% for choice in question.choice_set.all %}
            <li class="text-light">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
            <br>
        {% endfor %}
    </ul>
    <a href="{% url 'IntekMovieFridayPollapp:detail' question.id %}">Vote again?</a>
{% endblock %}